// Generated by CoffeeScript 1.7.1

  var app, express, http, path;

  express = require('express');

  http = require('http');

  path = require('path');

  app = express();

  app.set('port', process.env.PORT || 3000);

  app.set('views', path.join(__dirname, 'views'));

  app.set('view engine', 'jade');

  app.set('view options', {
    layout: false
  });

  app.use(express.favicon);

  app.use(express.json);

  app.use(express.urlencoded);

  app.use(express.methodOverride);

  app.use(app.router);

  app.use(express["static"](path.join(__dirname, 'public')));


  /* 
  ----------ROUTES--------
   */

  app.get('/', function(req, res) {
    return res.render('index');
  });


  /*
  --- WEBSERVER STARTUP --
   */

  app.listen(app.get('port'), function() {
    return console.log("Listening on port " + (app.get('port')));
  });

